global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rate-limiter-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rate-limiter-1:8080']
        labels:
          instance: 'gateway-1'

  - job_name: 'rate-limiter-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rate-limiter-2:8080']
        labels:
          instance: 'gateway-2'
